[package]
name = "Numproc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.4"
reqwest = "0.11.16"
tokio = { version = "1.27.0", features = ["full"] }
